
package org.crossover.server.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-29T17:39:28.819-03:00
 * Generated source version: 3.1.1
 * 
 */
public final class CompileService_CompileServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.server.crossover.org/", "compileService");

    private CompileService_CompileServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CompileService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CompileService_Service ss = new CompileService_Service(wsdlURL, SERVICE_NAME);
        CompileService port = ss.getCompileServiceImplPort();  
        
        {
        System.out.println("Invoking findCompilation...");
        org.crossover.server.ws.Compilation _findCompilation_arg0 = null;
        try {
            org.crossover.server.ws.Compilation _findCompilation__return = port.findCompilation(_findCompilation_arg0);
            System.out.println("findCompilation.result=" + _findCompilation__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking compile...");
        org.crossover.server.ws.Compilation _compile_arg0 = null;
        try {
            org.crossover.server.ws.Compilation _compile__return = port.compile(_compile_arg0);
            System.out.println("compile.result=" + _compile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
