package org.crossover.server.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-29T17:39:28.921-03:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://ws.server.crossover.org/", name = "CompileService")
@XmlSeeAlso({ObjectFactory.class})
public interface CompileService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCompilation", targetNamespace = "http://ws.server.crossover.org/", className = "org.crossover.server.ws.FindCompilation")
    @WebMethod
    @ResponseWrapper(localName = "findCompilationResponse", targetNamespace = "http://ws.server.crossover.org/", className = "org.crossover.server.ws.FindCompilationResponse")
    public org.crossover.server.ws.Compilation findCompilation(
        @WebParam(name = "arg0", targetNamespace = "")
        org.crossover.server.ws.Compilation arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "compile", targetNamespace = "http://ws.server.crossover.org/", className = "org.crossover.server.ws.Compile")
    @WebMethod
    @ResponseWrapper(localName = "compileResponse", targetNamespace = "http://ws.server.crossover.org/", className = "org.crossover.server.ws.CompileResponse")
    public org.crossover.server.ws.Compilation compile(
        @WebParam(name = "arg0", targetNamespace = "")
        org.crossover.server.ws.Compilation arg0
    ) throws Exception_Exception;
}
