
package org.crossover.server.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-29T17:39:28.899-03:00
 * Generated source version: 3.1.1
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.server.crossover.org/")
public class Exception_Exception extends java.lang.Exception {
    
    private org.crossover.server.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, org.crossover.server.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, org.crossover.server.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.crossover.server.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
